# Generated by Django 5.2.5 on 2025-08-18 17:43

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Минимум 2 символа')], verbose_name='SLUG для запросов')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 48x48px', null=True, upload_to='categories/', verbose_name='Иконка')),
                ('hint', models.CharField(help_text='10 - 150 символов', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Минимум 10 символов')], verbose_name='Подсказка (краткое описание)')),
                ('skills', django_ckeditor_5.fields.CKEditor5Field(help_text='Форматированный текст с HTML', verbose_name='Описание навыков')),
                ('resume', models.FileField(blank=True, help_text='Файл резюме', null=True, upload_to='resume', verbose_name='Резюме')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория деятельности',
                'verbose_name_plural': 'Категории деятельности',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 100 символов', max_length=100, verbose_name='Название проекта')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1200x800px', upload_to='projects/', verbose_name='Главное изображение')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Форматированный текст с HTML', verbose_name='Полное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Запись обновлена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Проект опубликован')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Катгория проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 100 символов', max_length=100, verbose_name='Название изображения')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1200x800px', upload_to='projects/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, help_text='Максимум 300 символов', max_length=300, verbose_name='Описание изображения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Дополнитнльное изображение',
                'verbose_name_plural': 'Дополнитнльные изображения',
                'ordering': ['project'],
            },
        ),
    ]
