# Generated by Django 4.1 on 2025-08-23 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Минимум 2 символа')], verbose_name='SLUG для запросов')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 48x48px', null=True, upload_to='categories/', verbose_name='Иконка')),
                ('hint', models.CharField(help_text='10 - 150 символов', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Минимум 10 символов')], verbose_name='Подсказка (краткое описание)')),
                ('skills', django_ckeditor_5.fields.CKEditor5Field(help_text='Форматированный текст с HTML', verbose_name='Описание навыков')),
                ('resume', models.FileField(blank=True, help_text='Файл резюме', null=True, upload_to='resume', verbose_name='Резюме')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория деятельности',
                'verbose_name_plural': 'Категории деятельности',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.projectcategory', verbose_name='Катгория проекта'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
