# Generated by Django 4.1 on 2025-08-27 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projectcategory_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='short_description',
            field=models.TextField(help_text='50 - 300 символов', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(50, 'Минимум 50 символов')], verbose_name='Ккраткое описание'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='hint',
            field=models.CharField(help_text='До 150 символов', max_length=150, null=True, verbose_name='Подсказка для кнопки'),
        ),
    ]
